window.APP_DATA = {
  "version": "2026.05.20-wku-eats-capture-calibrated-v10",
  "app": {
    "titleKo": "원광 이츠",
    "titleEn": "WKU Eats",
    "subtitleKo": "캡처본 기준 위치 정확도 개선",
    "subtitleEn": "Pins calibrated from user screenshots"
  },
  "campus": {
    "nameKo": "원광대학교",
    "nameEn": "Wonkwang University",
    "address": "전북특별자치도 익산시 익산대로 460 원광대학교",
    "lat": 35.9689881,
    "lng": 126.9537852,
    "sourceLabel": "원광대학교 공식 찾아오시는 길",
    "checkedDate": "2026.05.20",
    "sourceUrl": "https://www.wku.ac.kr/about/campus-info/road-map.html"
  },
  "restaurants": [
    {
      "id": "starbucks-wku",
      "nameKo": "스타벅스 익산원광대점",
      "nameEn": "Starbucks Iksan WKU",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 무왕로 888",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.5,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 디저트39 동쪽·파리바게뜨 서쪽",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "카페라떼",
          "en": "Caffe latte",
          "price": null
        }
      ],
      "foodKo": "글로벌 브랜드 카페라서 외국인 유학생도 메뉴를 이해하기 쉽다.",
      "foodEn": "A global café brand that is easy for international students to use.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 3,
      "lat": 35.96472,
      "lng": 126.95478,
      "searchQuery": "스타벅스 익산원광대점 전북 익산시 무왕로 888",
      "priority": 1,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "dessert39-wku",
      "nameKo": "디저트39 익산원광대점",
      "nameEn": "Dessert39 WKU",
      "category": "카페",
      "subCategory": "디저트",
      "subCategoryEn": "Dessert",
      "address": "전북특별자치도 익산시 무왕로 884 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.5,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 무왕로 디저트39 핀",
      "sourceUrl": "https://adcong.tistory.com/entry/%EC%9B%90%EA%B4%91%EB%8C%80-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B8-TOP-10-%EC%B6%94%EC%B2%9C",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "디저트",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "디저트 케이크",
          "en": "Dessert cake",
          "price": null
        }
      ],
      "foodKo": "음료와 디저트를 함께 고르기 쉬운 카페형 디저트 매장이다.",
      "foodEn": "A dessert café where drinks and cakes are easy to choose.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96475,
      "lng": 126.95424,
      "searchQuery": "디저트39 익산원광대점 전북 익산시 무왕로 884",
      "priority": 2,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "paris-baguette-wku",
      "nameKo": "파리바게뜨 원광대점",
      "nameEn": "Paris Baguette WKU",
      "category": "카페",
      "subCategory": "베이커리",
      "subCategoryEn": "Bakery",
      "address": "전북특별자치도 익산시 무왕로 896",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 무왕로 파리바게뜨 핀",
      "sourceUrl": "https://adcong.tistory.com/entry/%EC%9B%90%EA%B4%91%EB%8C%80-%EB%A7%9B%EC%A7%91-%EB%B2%A0%EC%8A%A4%ED%8A%B8-TOP-10-%EC%B6%94%EC%B2%9C",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "베이커리",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "샌드위치",
          "en": "Sandwich",
          "price": null
        },
        {
          "ko": "빵·커피",
          "en": "Bread and coffee",
          "price": null
        }
      ],
      "foodKo": "빵, 샌드위치, 커피를 함께 살 수 있어 간단한 아침이나 간식에 좋다.",
      "foodEn": "Good for a quick breakfast, bread, sandwiches, and coffee.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "샌드위치 하나 주세요.",
      "orderPhraseEn": "One Sandwich, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96474,
      "lng": 126.95622,
      "searchQuery": "파리바게뜨 익산원광대점 전북 익산시 무왕로 896",
      "priority": 3,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "india-1989",
      "nameKo": "1989인도",
      "nameEn": "1989 India",
      "category": "음식점",
      "subCategory": "인도음식",
      "subCategoryEn": "Indian food",
      "address": "전북특별자치도 익산시 익산대로70길 35-1 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.7,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 1989인도 라벨",
      "sourceUrl": "https://guigui93.tistory.com/36",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "인도음식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커리",
          "en": "Curry",
          "price": null
        },
        {
          "ko": "난",
          "en": "Naan",
          "price": null
        }
      ],
      "foodKo": "커리와 난을 중심으로 한 인도 음식점이다. 매운 정도를 확인하고 주문하면 좋다.",
      "foodEn": "An Indian restaurant focused on curry and naan. Ask about spice level before ordering.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "커리 하나랑 난 주세요.",
      "orderPhraseEn": "One curry and naan, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.96355,
      "lng": 126.95506,
      "searchQuery": "1989인도 전북 익산시 익산대로70길 35-1",
      "priority": 4,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "soryonggak",
      "nameKo": "소룡각",
      "nameEn": "Soryonggak",
      "category": "음식점",
      "subCategory": "중식",
      "subCategoryEn": "Chinese food",
      "address": "전북특별자치도 익산시 무왕로4길 12-17",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.1,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 소룡각 라벨",
      "sourceUrl": "https://www.imaeil.com/page/view/2019022220210244221",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "중식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "짜장면",
          "en": "Jajangmyeon",
          "price": null
        },
        {
          "ko": "짬뽕",
          "en": "Jjamppong",
          "price": null
        }
      ],
      "foodKo": "짜장면과 짬뽕 같은 한국식 중화요리를 먹을 수 있는 식당이다.",
      "foodEn": "A Korean-Chinese restaurant for jajangmyeon and jjamppong.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "짜장면 하나 주세요.",
      "orderPhraseEn": "One jajangmyeon, please.",
      "spice": 4,
      "priceLevel": 2,
      "lat": 35.96225,
      "lng": 126.95438,
      "searchQuery": "소룡각 전북 익산시 무왕로4길 12-17",
      "priority": 5,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "baekya",
      "nameKo": "백야",
      "nameEn": "Baekya",
      "category": "음식점",
      "subCategory": "일식",
      "subCategoryEn": "Japanese food",
      "address": "전북특별자치도 익산시 익산대로68길 27 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 2.7,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 백야 라벨",
      "sourceUrl": "https://life-in-house.tistory.com/entry/%EC%A0%84%EB%B6%81%EC%9D%B5%EC%82%B0-%EC%9B%90%EA%B4%91%EB%8C%80%ED%95%99%EA%B5%90-%EB%8C%80%ED%95%99%EB%A1%9C-%ED%95%AD%EC%A0%95%EC%82%B4-%EB%8D%AE%EB%B0%A5-%EB%A7%9B%EC%A7%91-%EB%B0%B1%EC%95%BC",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "일식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "돈카츠",
          "en": "Pork cutlet",
          "price": null
        },
        {
          "ko": "덮밥",
          "en": "Rice bowl",
          "price": null
        }
      ],
      "foodKo": "혼밥으로 먹기 좋은 일식·덮밥류 식당이다.",
      "foodEn": "A Japanese-style rice bowl or cutlet place suitable for solo dining.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "돈카츠 하나 주세요.",
      "orderPhraseEn": "One Pork cutlet, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96135,
      "lng": 126.95502,
      "searchQuery": "백야 익산 익산대로68길 27",
      "priority": 6,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "iksan-gimbapshop",
      "nameKo": "익산김밥샵 본점",
      "nameEn": "Iksan Gimbap Shop",
      "category": "음식점",
      "subCategory": "김밥",
      "subCategoryEn": "Gimbap",
      "address": "전북특별자치도 익산시 익산대로68길 32 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 3.8,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 익산김밥샵 본점 라벨",
      "sourceUrl": "https://www.114.co.kr/search/detail?comp_id=13363623&comp_tp_cd=TEL&upjong_cd=852105",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "김밥",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "김밥",
          "en": "Gimbap",
          "price": null
        },
        {
          "ko": "라면",
          "en": "Ramyeon",
          "price": null
        }
      ],
      "foodKo": "김밥은 밥, 채소, 단무지 등을 김으로 말아 먹는 한국식 간편식이다.",
      "foodEn": "Gimbap is a simple Korean roll with rice, vegetables, and seaweed.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "김밥 한 줄 주세요.",
      "orderPhraseEn": "One roll of gimbap, please.",
      "spice": 2,
      "priceLevel": 1,
      "lat": 35.96092,
      "lng": 126.95545,
      "searchQuery": "익산김밥샵 본점 익산대로68길 32",
      "priority": 7,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "tteok-dukeop",
      "nameKo": "떡두껍집",
      "nameEn": "Tteokdukeopjip",
      "category": "음식점",
      "subCategory": "분식",
      "subCategoryEn": "Korean snacks",
      "address": "전북특별자치도 익산시 익산대로68길 36 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.2,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 떡두껍집 라벨",
      "sourceUrl": "https://www.siksinhot.com/P/411922",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "분식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "떡볶이",
          "en": "Tteokbokki",
          "price": null
        },
        {
          "ko": "튀김",
          "en": "Fried snacks",
          "price": null
        }
      ],
      "foodKo": "떡볶이는 매콤한 고추장 소스에 떡을 넣어 먹는 대표적인 분식이다.",
      "foodEn": "Tteokbokki is a spicy rice cake dish with gochujang sauce.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "떡볶이 1인분 주세요.",
      "orderPhraseEn": "One serving of tteokbokki, please.",
      "spice": 4,
      "priceLevel": 1,
      "lat": 35.96096,
      "lng": 126.95618,
      "searchQuery": "떡두껍집 전북 익산시 익산대로68길 36",
      "priority": 8,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "jeonsutdak",
      "nameKo": "전주숯불닭집 전숯닭",
      "nameEn": "Jeonju Charcoal Chicken",
      "category": "음식점",
      "subCategory": "치킨",
      "subCategoryEn": "Korean chicken",
      "address": "전북특별자치도 익산시 익산대로54길 80 1~2층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.9,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 전주숯불닭집 전숯닭 라벨",
      "sourceUrl": "https://moneypin.biz/bizno/detail/8521202042/",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "치킨",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "숯불닭갈비",
          "en": "Charcoal-grilled chicken",
          "price": null
        },
        {
          "ko": "닭구이",
          "en": "Grilled chicken",
          "price": null
        }
      ],
      "foodKo": "숯불 향이 나는 닭구이·닭갈비 계열 식당이다.",
      "foodEn": "A charcoal-grilled chicken restaurant.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "숯불닭갈비 하나 주세요.",
      "orderPhraseEn": "One charcoal-grilled chicken, please.",
      "spice": 3,
      "priceLevel": 2,
      "lat": 35.96012,
      "lng": 126.95634,
      "searchQuery": "전주숯불닭집 전숯닭 원광대점 익산대로54길 80",
      "priority": 9,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "twosome-wku",
      "nameKo": "투썸플레이스 원광대점",
      "nameEn": "A Twosome Place WKU",
      "category": "카페",
      "subCategory": "디저트",
      "subCategoryEn": "Dessert",
      "address": "전북특별자치도 익산시 동서로5길 91 2층·3층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 투썸플레이스 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "디저트",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "케이크",
          "en": "Cake",
          "price": null
        }
      ],
      "foodKo": "케이크와 커피 조합으로 많이 이용하는 프랜차이즈 카페다.",
      "foodEn": "A franchise café known for coffee and cakes.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 3,
      "lat": 35.95948,
      "lng": 126.95655,
      "searchQuery": "투썸플레이스 원광대점 동서로5길 91",
      "priority": 10,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "sulbing-wku",
      "nameKo": "설빙 원광대점",
      "nameEn": "Sulbing WKU",
      "category": "카페",
      "subCategory": "빙수",
      "subCategoryEn": "Bingsu dessert",
      "address": "전북특별자치도 익산시 익산대로54길 87-1 2층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 3.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 설빙 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "빙수",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "인절미빙수",
          "en": "Injeolmi bingsu",
          "price": null
        },
        {
          "ko": "딸기빙수",
          "en": "Strawberry bingsu",
          "price": null
        }
      ],
      "foodKo": "빙수는 얼음을 곱게 갈아 토핑과 함께 먹는 한국식 디저트다.",
      "foodEn": "Bingsu is a Korean shaved-ice dessert with toppings.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "인절미빙수 하나 주세요.",
      "orderPhraseEn": "One injeolmi bingsu, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96216,
      "lng": 126.95656,
      "searchQuery": "설빙 원광대점 익산대로54길 87-1",
      "priority": 11,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "mega-mgc-wku",
      "nameKo": "메가MGC커피 원광대점",
      "nameEn": "Mega MGC Coffee WKU",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 무왕로4길 18 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 1.9,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 메가MGC커피 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "라떼",
          "en": "Latte",
          "price": null
        }
      ],
      "foodKo": "저가형 커피 프랜차이즈로 테이크아웃에 편하다.",
      "foodEn": "A budget coffee franchise convenient for takeaway.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 1,
      "lat": 35.9624,
      "lng": 126.95722,
      "searchQuery": "메가MGC커피 원광대점 무왕로4길 18",
      "priority": 12,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "kagong-campus",
      "nameKo": "카공캠퍼스 익산원광대점",
      "nameEn": "Kagong Campus Café",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 익산대로70길 45-1 2층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 현재 위치 근처 카페 클러스터",
      "sourceUrl": "https://www.instagram.com/kagongcampus/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "공부용 음료",
          "en": "Study drink",
          "price": null
        }
      ],
      "foodKo": "공부하기 좋은 카페 콘셉트의 장소다.",
      "foodEn": "A café concept suitable for studying.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.9627,
      "lng": 126.95668,
      "searchQuery": "카공캠퍼스 익산원광대점 익산대로70길 45-1",
      "priority": 13,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "loen",
      "nameKo": "로엔",
      "nameEn": "Loen",
      "category": "음식점",
      "subCategory": "일반음식",
      "subCategoryEn": "Restaurant",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 로엔",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 로엔은 카페가 아니라 음식점 아이콘 위치로 분류",
      "sourceUrl": "https://localmap.co.kr/web/splus/kmap/list.php?gugun=4680000&keyarea=%EC%8B%A0%EB%8F%99&keyno=154&sigun=6450000",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "양식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "스테이크·파스타",
          "en": "Steak or pasta",
          "price": null
        },
        {
          "ko": "추천 메뉴",
          "en": "Recommended menu",
          "price": null
        }
      ],
      "foodKo": "지도 캡처상 음식점 아이콘으로 확인되는 원광대 대학로 주변 음식점이다.",
      "foodEn": "A restaurant around WKU campus street, identified as a food place in the screenshot.",
      "cultureKo": "처음 방문할 때는 지도 앱에서 영업 여부를 한 번 더 확인하는 것이 좋습니다.",
      "cultureEn": "For small campus restaurants, it is best to recheck opening status in a map app before visiting.",
      "orderPhraseKo": "추천 메뉴 하나 주세요.",
      "orderPhraseEn": "One recommended menu, please.",
      "spice": 1,
      "priceLevel": 3,
      "lat": 35.963,
      "lng": 126.95856,
      "searchQuery": "로엔 원광대 익산",
      "priority": 14,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "hwangje-jjamppong",
      "nameKo": "황제짬뽕 원광대본점",
      "nameEn": "Hwangje Jjamppong",
      "category": "음식점",
      "subCategory": "중식",
      "subCategoryEn": "Chinese food",
      "address": "전북특별자치도 익산시 익산대로68길 51 씨즈퍼스트상가 121호",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 로엔 동쪽·동서로21길 인근 황제짬뽕 핀",
      "sourceUrl": "https://www.114.co.kr/life/localBillStore/detail/383649",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "중식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "짬뽕",
          "en": "Jjamppong",
          "price": null
        },
        {
          "ko": "짜장면",
          "en": "Jajangmyeon",
          "price": null
        }
      ],
      "foodKo": "짬뽕은 매운 국물, 면, 채소, 해산물이 들어간 한국식 중화요리다.",
      "foodEn": "Jjamppong is a spicy Korean-Chinese noodle soup with seafood and vegetables.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "짬뽕 하나 주세요.",
      "orderPhraseEn": "One jjamppong, please.",
      "spice": 4,
      "priceLevel": 2,
      "lat": 35.96272,
      "lng": 126.95912,
      "searchQuery": "황제짬뽕 원광대본점 전북 익산시 익산대로68길 51 씨즈퍼스트상가 121호",
      "priority": 15,
      "descriptionKo": "씨즈퍼스트상가 121호에 있는 원광대 대학로 중식당입니다. 쟁반짜장, 짬뽕, 탕수육을 확인하세요.",
      "descriptionEn": "A Chinese restaurant in Seize First Shopping Arcade #121 near WKU. Check jjamppong, tray jajangmyeon, and tangsuyuk.",
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "frank-coffinbar",
      "nameKo": "프랭크커핀바 익산점",
      "nameEn": "Frank Coffin Bar",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 동서로5길 106 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.7,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 프랭크커핀바 라벨",
      "sourceUrl": "https://www.instagram.com/p/DElhRR-TI2n/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "커피와 디저트를 즐길 수 있는 카페다.",
      "foodEn": "A café for coffee and desserts.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.9605,
      "lng": 126.95928,
      "searchQuery": "프랭크커핀바 익산점 동서로5길 106",
      "priority": 16,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "kongbul",
      "nameKo": "콩불",
      "nameEn": "Kongbul",
      "category": "음식점",
      "subCategory": "한식",
      "subCategoryEn": "Korean food",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 콩불",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 콩불 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "콩불",
          "en": "Spicy bean sprout pork",
          "price": null
        },
        {
          "ko": "볶음밥",
          "en": "Fried rice",
          "price": null
        }
      ],
      "foodKo": "콩불은 콩나물과 돼지고기를 매콤하게 볶아 먹는 한국식 메뉴다.",
      "foodEn": "Kongbul is a spicy Korean stir-fry with bean sprouts and pork.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "콩불 2인분 주세요.",
      "orderPhraseEn": "Two servings of kongbul, please.",
      "spice": 4,
      "priceLevel": 2,
      "lat": 35.95928,
      "lng": 126.95798,
      "searchQuery": "콩불 원광대 익산",
      "priority": 17,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "yeoun",
      "nameKo": "여운",
      "nameEn": "Yeoun",
      "category": "음식점",
      "subCategory": "한식",
      "subCategoryEn": "Korean food",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 여운",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 여운 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "한식 메뉴",
          "en": "Korean meal",
          "price": null
        },
        {
          "ko": "추천 메뉴",
          "en": "Recommended menu",
          "price": null
        }
      ],
      "foodKo": "원광대 동네에서 식사하기 좋은 한식 계열 장소다.",
      "foodEn": "A Korean-style dining place around WKU.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "한식 메뉴 하나 주세요.",
      "orderPhraseEn": "One Korean meal, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.9592,
      "lng": 126.95862,
      "searchQuery": "여운 원광대 익산",
      "priority": 18,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "bluebones",
      "nameKo": "블루본즈",
      "nameEn": "Blue Bones",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 동서로5길 116 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.7,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 블루본즈 라벨",
      "sourceUrl": "https://www.instagram.com/p/DUsk0yVkw27/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "스크린샷상 카페 아이콘 위치에 맞춰 넣은 카페다.",
      "foodEn": "A café marker placed according to the provided screenshot.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96044,
      "lng": 126.96082,
      "searchQuery": "블루본즈 익산본점 동서로5길 116",
      "priority": 19,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "ssakssak-burrito",
      "nameKo": "싹싹브리또",
      "nameEn": "Ssaksak Burrito",
      "category": "음식점",
      "subCategory": "브리또",
      "subCategoryEn": "Burrito",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 싹싹브리또",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 싹싹브리또 라벨",
      "sourceUrl": "https://jobs.daangn.com/job-posts/%EC%8B%B9%EC%8B%B9%EB%B8%8C%EB%A6%AC%EB%98%90-%EC%9D%B5%EC%82%B0%EC%A0%90%EA%B3%BC-%ED%95%A8%EA%BB%98%ED%95%98%EC%8B%A4-%EB%B6%84-EMyCQS13EHp",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "브리또",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "브리또",
          "en": "Burrito",
          "price": null
        },
        {
          "ko": "타코류",
          "en": "Taco-style menu",
          "price": null
        }
      ],
      "foodKo": "브리또처럼 간편하게 먹기 좋은 메뉴를 제공하는 장소다.",
      "foodEn": "A casual place for burritos and simple meals.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "브리또 하나 주세요.",
      "orderPhraseEn": "One burrito, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.96118,
      "lng": 126.96086,
      "searchQuery": "싹싹브리또 원광대 익산",
      "priority": 20,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "sindong-crab",
      "nameKo": "신동꽃게장",
      "nameEn": "Sindong Kkotgejang",
      "category": "음식점",
      "subCategory": "게장",
      "subCategoryEn": "Soy-marinated crab",
      "address": "전북특별자치도 익산시 동서로21길 72-1 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.6,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 신동꽃게장 라벨",
      "sourceUrl": "https://bizno.net/article/7661200781",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "게장",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "꽃게장",
          "en": "Marinated crab",
          "price": null
        },
        {
          "ko": "게장 정식",
          "en": "Marinated crab set",
          "price": null
        }
      ],
      "foodKo": "게장은 간장이나 양념에 게를 절여 먹는 한국 음식이다.",
      "foodEn": "Gejang is Korean marinated crab, often soy-based or spicy.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "게장 정식 하나 주세요.",
      "orderPhraseEn": "One marinated crab set, please.",
      "spice": 2,
      "priceLevel": 3,
      "lat": 35.95936,
      "lng": 126.96042,
      "searchQuery": "신동꽃게장 익산 동서로21길 72-1",
      "priority": 21,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "damae-kkot",
      "nameKo": "담애꽃",
      "nameEn": "Damae Kkot",
      "category": "음식점",
      "subCategory": "한식",
      "subCategoryEn": "Korean food",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 담애꽃",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 담애꽃 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "한식 메뉴",
          "en": "Korean meal",
          "price": null
        },
        {
          "ko": "추천 메뉴",
          "en": "Recommended menu",
          "price": null
        }
      ],
      "foodKo": "원광대 아래쪽 생활권에 위치한 한식 계열 식당이다.",
      "foodEn": "A Korean restaurant in the lower WKU neighborhood area.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "한식 메뉴 하나 주세요.",
      "orderPhraseEn": "One Korean meal, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.95848,
      "lng": 126.95625,
      "searchQuery": "담애꽃 원광대 익산",
      "priority": 22,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "migung",
      "nameKo": "미강",
      "nameEn": "Migung",
      "category": "카페",
      "subCategory": "카페",
      "subCategoryEn": "Cafe",
      "address": "전북특별자치도 익산시 신동 원광대 대학로 미강",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 미강 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심",
        "카페"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "한식 메뉴",
          "en": "Korean meal",
          "price": null
        },
        {
          "ko": "추천 메뉴",
          "en": "Recommended menu",
          "price": null
        }
      ],
      "foodKo": "스크린샷의 남동쪽 식당 밀집 구역에 맞춰 재배치했다.",
      "foodEn": "Placed in the southeast food cluster from the screenshot.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "한식 메뉴 하나 주세요.",
      "orderPhraseEn": "One Korean meal, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.95878,
      "lng": 126.95686,
      "searchQuery": "미강 원광대 익산",
      "priority": 23,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "jeongjeong-bangbang",
      "nameKo": "정정방방",
      "nameEn": "Jeongjeong Bangbang",
      "category": "카페",
      "subCategory": "카페",
      "subCategoryEn": "Cafe",
      "address": "전북특별자치도 익산시 동서로5길 104 2층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 정정방방 라벨",
      "sourceUrl": "https://www.instagram.com/p/DUsjBpRE4uc/",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심",
        "카페"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "한식 메뉴",
          "en": "Korean meal",
          "price": null
        },
        {
          "ko": "추천 메뉴",
          "en": "Recommended menu",
          "price": null
        }
      ],
      "foodKo": "미강 주변에 있는 식당 밀집 구역의 장소다.",
      "foodEn": "A restaurant in the same food cluster near Migung.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "한식 메뉴 하나 주세요.",
      "orderPhraseEn": "One Korean meal, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.9588,
      "lng": 126.95748,
      "searchQuery": "정정방방 익산 동서로5길 104",
      "priority": 24,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "mar-rueda",
      "nameKo": "마루에다",
      "nameEn": "Mar Rueda",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 무왕로 866-7",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 서쪽 마루에다 핀",
      "sourceUrl": "https://www.instagram.com/p/C1LZG4iySHw/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "원광대 서쪽 카페 구역에 있는 카페다.",
      "foodEn": "A café in the west-side WKU café area.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.9631,
      "lng": 126.95348,
      "searchQuery": "마루에다 익산 무왕로 866-7",
      "priority": 25,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "slow1002",
      "nameKo": "슬로우1002",
      "nameEn": "Slow 1002",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 익산대로70길 8",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 서쪽 슬로우1002 핀",
      "sourceUrl": "https://www.instagram.com/p/DP8eHQiEVyv/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "조용히 쉬거나 공부하기 좋은 카페로 표시했다.",
      "foodEn": "A café marked for resting or studying.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.9625,
      "lng": 126.95328,
      "searchQuery": "슬로우1002 익산 익산대로70길 8",
      "priority": 26,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "sindong-coffee",
      "nameKo": "신동커피",
      "nameEn": "Sindong Coffee",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 무왕로 878-13 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 4.9,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 신동커피 핀",
      "sourceUrl": "https://www.instagram.com/p/DVSEoP-EfM2/",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "라떼",
          "en": "Latte",
          "price": null
        }
      ],
      "foodKo": "원광대 근처 로컬 커피 매장이다.",
      "foodEn": "A local coffee shop near WKU.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.96372,
      "lng": 126.95568,
      "searchQuery": "신동커피 전북 익산시 무왕로 878-13",
      "priority": 27,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "selecto-coffee",
      "nameKo": "셀렉토커피",
      "nameEn": "Selecto Coffee",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 무왕로4길 32 2층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 셀렉토커피 라벨",
      "sourceUrl": "https://pervsi.com/info/m.php?board=pejb&command=body&no=187324",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "아메리카노",
          "en": "Americano",
          "price": null
        },
        {
          "ko": "라떼",
          "en": "Latte",
          "price": null
        }
      ],
      "foodKo": "남쪽 카페 구역에 있는 프랜차이즈 카페다.",
      "foodEn": "A franchise café in the south café area.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "아메리카노 하나 주세요.",
      "orderPhraseEn": "One Americano, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.95858,
      "lng": 126.95866,
      "searchQuery": "셀렉토커피 원광대점 무왕로4길 32",
      "priority": 28,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "abide",
      "nameKo": "어바이드",
      "nameEn": "Abide",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 동서로5길 76 부근",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 5.0,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 어바이드 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "셀렉토커피 근처 카페 구역에 맞춰 배치했다.",
      "foodEn": "Placed in the café cluster near Selecto Coffee.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.95828,
      "lng": 126.95912,
      "searchQuery": "어바이드 익산 동서로5길 76",
      "priority": 29,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "jigeum-yeogi",
      "nameKo": "지금여기",
      "nameEn": "Jigeum Yeogi",
      "category": "카페",
      "subCategory": "커피",
      "subCategoryEn": "Coffee",
      "address": "전북특별자치도 익산시 동서로11길 5",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": 3.6,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 지금여기 라벨",
      "sourceUrl": "",
      "checkedDate": "2026.05.20",
      "tags": [
        "카페",
        "커피",
        "원광대",
        "유학생 추천",
        "카페",
        "디저트",
        "공부"
      ],
      "features": [
        "카페·디저트 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "커피",
          "en": "Coffee",
          "price": null
        },
        {
          "ko": "디저트",
          "en": "Dessert",
          "price": null
        }
      ],
      "foodKo": "남쪽 주거지 근처의 카페 위치로 표시했다.",
      "foodEn": "A café marker in the south residential area.",
      "cultureKo": "한국 카페는 공부, 대화, 디저트 이용이 함께 이루어지는 캠퍼스 생활 공간입니다.",
      "cultureEn": "Korean cafés around campus are commonly used for studying, talking, and desserts.",
      "orderPhraseKo": "커피 하나 주세요.",
      "orderPhraseEn": "One Coffee, please.",
      "spice": 1,
      "priceLevel": 2,
      "lat": 35.95748,
      "lng": 126.95918,
      "searchQuery": "지금여기 익산 동서로11길 5",
      "priority": 30,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "jjampponggwan",
      "nameKo": "짬뽕관 익산원광대점",
      "nameEn": "Jjampponggwan",
      "category": "음식점",
      "subCategory": "중식",
      "subCategoryEn": "Chinese food",
      "address": "전북특별자치도 익산시 익산대로68길 31 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 중앙 음식점 클러스터",
      "sourceUrl": "https://www.xn--zb0bq16amwh.com/shopinfo/103?page=3",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "중식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "짬뽕",
          "en": "Jjamppong",
          "price": 10000
        },
        {
          "ko": "짜장면",
          "en": "Jajangmyeon",
          "price": 8000
        }
      ],
      "foodKo": "한국식 중화요리인 짬뽕, 짜장면을 먹을 수 있는 식당이다.",
      "foodEn": "A Korean-Chinese restaurant for jjamppong and jajangmyeon.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "짬뽕 하나 주세요.",
      "orderPhraseEn": "One jjamppong, please.",
      "spice": 4,
      "priceLevel": 2,
      "lat": 35.96274,
      "lng": 126.95642,
      "searchQuery": "짬뽕관 익산원광대점 전북 익산시 익산대로68길 31",
      "priority": 31,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "baeksojeong",
      "nameKo": "백소정 익산원광대점",
      "nameEn": "Baeksojeong",
      "category": "음식점",
      "subCategory": "일식",
      "subCategoryEn": "Japanese food",
      "address": "전북특별자치도 익산시 익산대로68길 32 2층 1호",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 중앙 음식점 클러스터",
      "sourceUrl": "https://www.ecoyouguide.com/html_file.php?file=upso_list_stat_detail.html&get_end_date=&get_g=0&get_gu=196&get_h=0&get_k=&get_lv=0&get_si=27&get_start_date=&get_t=0&p=5&search_category1=&search_category2=",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "일식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "마제소바",
          "en": "Maze soba",
          "price": null
        },
        {
          "ko": "돈카츠",
          "en": "Pork cutlet",
          "price": null
        }
      ],
      "foodKo": "마제소바와 돈카츠를 중심으로 하는 일식 계열 식당이다.",
      "foodEn": "A Japanese-style restaurant focused on maze soba and pork cutlet.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "마제소바 하나 주세요.",
      "orderPhraseEn": "One Maze soba, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.96252,
      "lng": 126.95652,
      "searchQuery": "백소정 익산원광대점 전북 익산시 익산대로68길 32",
      "priority": 32,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "bobae",
      "nameKo": "보배반점 익산원광대점",
      "nameEn": "Bobae Banjeom",
      "category": "음식점",
      "subCategory": "중식",
      "subCategoryEn": "Chinese food",
      "address": "전북특별자치도 익산시 익산대로68길 34 1층",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 중앙 음식점 클러스터",
      "sourceUrl": "https://tabling.co.kr/place/68ecb32b36ac0da80290244a",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "중식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "짬뽕",
          "en": "Jjamppong",
          "price": null
        },
        {
          "ko": "탕수육",
          "en": "Tangsuyuk",
          "price": null
        }
      ],
      "foodKo": "짜장면, 짬뽕, 탕수육 같은 메뉴를 고르기 쉬운 중식당이다.",
      "foodEn": "A Chinese-style restaurant with familiar Korean-Chinese dishes.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "짬뽕 하나 주세요.",
      "orderPhraseEn": "One Jjamppong, please.",
      "spice": 4,
      "priceLevel": 2,
      "lat": 35.96245,
      "lng": 126.95682,
      "searchQuery": "보배반점 익산원광대점 전북 익산시 익산대로68길 34",
      "priority": 33,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    },
    {
      "id": "jangdo",
      "nameKo": "장도뚝배기 원광대점",
      "nameEn": "Jangdo Ttukbaegi",
      "category": "음식점",
      "subCategory": "한식",
      "subCategoryEn": "Korean food",
      "address": "전북특별자치도 익산시 익산대로68길 32",
      "area": "원광대 대학로 / WKU campus street",
      "phone": "확인 필요",
      "hours": "방문 전 지도 앱에서 확인 / Check before visiting",
      "closed": "확인 필요",
      "rating": null,
      "reviewCount": null,
      "sourceLabel": "사용자 캡처본 기준 재보정: 중앙 음식점 클러스터",
      "sourceUrl": "https://jdttukbaegi.com/sub/sub03_01.php",
      "checkedDate": "2026.05.20",
      "tags": [
        "음식점",
        "한식",
        "원광대",
        "유학생 추천",
        "식사",
        "맛집",
        "점심"
      ],
      "features": [
        "음식점 구분",
        "실제 주소 재확인",
        "지도 캡처 기준 위치 보정",
        "한글·영어 메뉴 설명",
        "외부 지도 앱 연결",
        "위치 전면 재보정",
        "주소·지도 캡처 대조",
        "사용자 캡처본 기준 위치 보정",
        "음식점/카페 아이콘 재확인"
      ],
      "menus": [
        {
          "ko": "뚝배기",
          "en": "Hot stone-bowl soup",
          "price": null
        },
        {
          "ko": "국밥",
          "en": "Soup rice",
          "price": null
        }
      ],
      "foodKo": "뚝배기는 뜨거운 그릇에 국물 음식을 담아 먹는 한국식 식사다.",
      "foodEn": "Ttukbaegi means soup or stew served in a hot stone bowl.",
      "cultureKo": "한국 대학가 식당은 빠른 식사, 혼밥, 친구와의 저녁 약속에 자주 이용됩니다.",
      "cultureEn": "Campus restaurants in Korea are commonly used for quick meals, solo dining, and dinner with friends.",
      "orderPhraseKo": "뚝배기 하나 주세요.",
      "orderPhraseEn": "One Hot stone-bowl soup, please.",
      "spice": 2,
      "priceLevel": 2,
      "lat": 35.96268,
      "lng": 126.95618,
      "searchQuery": "장도뚝배기 원광대점 익산대로68길 32",
      "priority": 34,
      "mapAccuracyKo": "사용자 캡처본 기준 핀 재보정",
      "mapAccuracyEn": "Pin recalibrated from user screenshots"
    }
  ],
  "routes": [
    {
      "title": "처음 온 유학생 기본 코스",
      "titleEn": "First-time student route",
      "desc": "식사와 디저트를 부담 없이 경험하는 코스",
      "descEn": "A simple meal-and-dessert route",
      "ids": [
        "iksan-gimbapshop",
        "hwangje-jjamppong",
        "sulbing-wku"
      ]
    },
    {
      "title": "카페 공부 코스",
      "titleEn": "Study café route",
      "desc": "커피를 마시며 공부하기 좋은 카페 중심 코스",
      "descEn": "A café route for studying with coffee",
      "ids": [
        "sindong-coffee",
        "frank-coffinbar",
        "abide"
      ]
    },
    {
      "title": "매운맛 체험 코스",
      "titleEn": "Spicy food route",
      "desc": "한국 대학가의 매운 메뉴를 체험하는 코스",
      "descEn": "Try spicy Korean campus food",
      "ids": [
        "hwangje-jjamppong",
        "tteok-dukeop",
        "mega-mgc-wku"
      ]
    },
    {
      "title": "친구와 저녁 코스",
      "titleEn": "Dinner with friends route",
      "desc": "함께 먹기 좋은 식당 위주의 코스",
      "descEn": "Restaurants suitable for dinner with friends",
      "ids": [
        "kongbul",
        "jeonsutdak",
        "twosome-wku"
      ]
    }
  ],
  "cultureTips": [
    {
      "title": "반찬 문화",
      "body": "한식당에서는 김치나 단무지 같은 기본 반찬이 함께 나오는 경우가 많다. 부족하면 ‘반찬 더 주세요’라고 말하면 된다.",
      "phrase": "반찬 더 주세요.",
      "titleEn": "Side dish culture",
      "bodyEn": "Korean restaurants often serve basic side dishes such as kimchi or pickled radish. If you need more, say “Banchan deo juseyo.”",
      "phraseEn": "More side dishes, please."
    },
    {
      "title": "물·셀프바",
      "body": "대학가 식당은 물, 앞접시, 반찬을 직접 가져가는 셀프 방식이 흔하다. 입구나 계산대 주변을 확인하자.",
      "phrase": "물은 셀프인가요?",
      "titleEn": "Water and self-service bar",
      "bodyEn": "Around campus, many restaurants let customers get water, small plates, and extra side dishes by themselves. Check near the entrance or counter.",
      "phraseEn": "Is the water self-service?"
    },
    {
      "title": "매운맛 확인",
      "body": "짬뽕, 닭갈비, 매운 돈까스는 생각보다 매울 수 있다. 주문 전 덜 맵게 가능한지 확인하면 안전하다.",
      "phrase": "덜 맵게 가능할까요?",
      "titleEn": "Checking spiciness",
      "bodyEn": "Jjamppong, dakgalbi, and spicy pork cutlet can be hotter than expected. Ask if the food can be made less spicy before ordering.",
      "phraseEn": "Can you make it less spicy?"
    },
    {
      "title": "키오스크 주문",
      "body": "프랜차이즈나 디저트 가게는 키오스크 주문이 많다. 메뉴 사진과 가격을 보며 천천히 고를 수 있다.",
      "phrase": "포장해 주세요.",
      "titleEn": "Kiosk ordering",
      "bodyEn": "Franchise and dessert shops often use kiosks. You can look at menu photos and prices slowly before choosing.",
      "phraseEn": "Please make it to go."
    },
    {
      "title": "식사 후 카페",
      "body": "한국 대학생들은 밥을 먹은 뒤 카페로 이동해 대화하거나 공부하는 경우가 많다. 지도에서 카페·디저트 필터를 활용하자.",
      "phrase": "아이스 아메리카노 하나 주세요.",
      "titleEn": "Cafe after meals",
      "bodyEn": "Korean university students often go to a cafe after eating to talk or study. Use the cafe and dessert filter on the map.",
      "phraseEn": "One iced Americano, please."
    }
  ],
  "mapNoteKo": "사용자가 제공한 네이버지도 캡처 4장을 기준으로 음식점·카페 핀을 다시 맞췄습니다. 외부 지도 버튼은 네이버·카카오·구글 검색으로 연결됩니다.",
  "mapNoteEn": "Pins were recalibrated using four user-provided Naver Map screenshots. External buttons open Naver, Kakao, and Google map searches.",
  "recheckNote": "v9: 황제짬뽕을 동서로21길 동쪽 씨즈퍼스트상가 위치로 재배치하고, 병원점/원광대점 혼동이 있었던 파리바게뜨·스타벅스 주소를 원광대 대학로 쪽으로 수정. 동서로5길·익산대로68길·무왕로4길 주변 카페/음식점의 핀을 전체 재보정함.",
  "locationAudit": {
    "methodKo": "① 캡처에 식당명이 보이는 지점은 해당 라벨 위치를 우선 적용 ② 음식점/카페 아이콘 종류를 재확인 ③ 주소 검색 결과와 충돌하는 곳은 캡처상 실제 핀 위치를 우선 적용 ④ 정확 좌표가 애매한 곳은 네이버/카카오/구글 지도 검색 버튼을 유지",
    "methodEn": "① Visible labels in the screenshots were prioritized ② restaurant/cafe icon types were rechecked ③ screenshot pin positions were prioritized when address-based placement looked wrong ④ external map search buttons are kept for ambiguous cases",
    "checkedDate": "2026.05.20",
    "count": 34
  }
};
